import 'persona_v2_contract.dart';

/// Native Frequency V2 (12D) unit-interval targets for each Persona.
///
/// Values are in [0, 1] after the signed→unit map. They are authored from
/// Persona behavioral definitions, not translated from Frequency V1 6D.
class PersonaV2FrequencyPrototypes {
  PersonaV2FrequencyPrototypes._();

  static const Map<String, Map<String, double>> unitTargets = {
    'uygulayici': {
      'contact_need': 0.45,
      'closeness_pace': 0.40,
      'initiative': 0.72,
      'autonomy': 0.55,
      'reassurance_need': 0.28,
      'uncertainty_tolerance': 0.32,
      'disclosure_pace': 0.36,
      'boundary_firmness': 0.70,
      'repair_style': 0.52,
      'social_energy': 0.58,
      'structure_preference': 0.88,
      'adaptability': 0.28,
    },
    'koruyucu': {
      'contact_need': 0.72,
      'closeness_pace': 0.55,
      'initiative': 0.48,
      'autonomy': 0.38,
      'reassurance_need': 0.48,
      'uncertainty_tolerance': 0.38,
      'disclosure_pace': 0.55,
      'boundary_firmness': 0.62,
      'repair_style': 0.78,
      'social_energy': 0.50,
      'structure_preference': 0.65,
      'adaptability': 0.42,
    },
    'bilge': {
      'contact_need': 0.40,
      'closeness_pace': 0.30,
      'initiative': 0.35,
      'autonomy': 0.68,
      'reassurance_need': 0.30,
      'uncertainty_tolerance': 0.62,
      'disclosure_pace': 0.28,
      'boundary_firmness': 0.58,
      'repair_style': 0.50,
      'social_energy': 0.32,
      'structure_preference': 0.55,
      'adaptability': 0.45,
    },
    'lider': {
      'contact_need': 0.55,
      'closeness_pace': 0.52,
      'initiative': 0.90,
      'autonomy': 0.55,
      'reassurance_need': 0.28,
      'uncertainty_tolerance': 0.62,
      'disclosure_pace': 0.58,
      'boundary_firmness': 0.68,
      'repair_style': 0.55,
      'social_energy': 0.70,
      'structure_preference': 0.60,
      'adaptability': 0.58,
    },
    'muhafiz': {
      'contact_need': 0.42,
      'closeness_pace': 0.35,
      'initiative': 0.48,
      'autonomy': 0.52,
      'reassurance_need': 0.35,
      'uncertainty_tolerance': 0.22,
      'disclosure_pace': 0.32,
      'boundary_firmness': 0.90,
      'repair_style': 0.45,
      'social_energy': 0.40,
      'structure_preference': 0.88,
      'adaptability': 0.25,
    },
    'sifaci': {
      'contact_need': 0.68,
      'closeness_pace': 0.58,
      'initiative': 0.45,
      'autonomy': 0.32,
      'reassurance_need': 0.42,
      'uncertainty_tolerance': 0.50,
      'disclosure_pace': 0.62,
      'boundary_firmness': 0.40,
      'repair_style': 0.90,
      'social_energy': 0.48,
      'structure_preference': 0.45,
      'adaptability': 0.62,
    },
    'yargic': {
      'contact_need': 0.40,
      'closeness_pace': 0.38,
      'initiative': 0.48,
      'autonomy': 0.58,
      'reassurance_need': 0.32,
      'uncertainty_tolerance': 0.48,
      'disclosure_pace': 0.45,
      'boundary_firmness': 0.72,
      'repair_style': 0.55,
      'social_energy': 0.42,
      'structure_preference': 0.70,
      'adaptability': 0.42,
    },
    'empat': {
      'contact_need': 0.78,
      'closeness_pace': 0.72,
      'initiative': 0.42,
      'autonomy': 0.28,
      'reassurance_need': 0.62,
      'uncertainty_tolerance': 0.48,
      'disclosure_pace': 0.75,
      'boundary_firmness': 0.32,
      'repair_style': 0.72,
      'social_energy': 0.55,
      'structure_preference': 0.38,
      'adaptability': 0.58,
    },
    'cesur': {
      'contact_need': 0.52,
      'closeness_pace': 0.58,
      'initiative': 0.82,
      'autonomy': 0.62,
      'reassurance_need': 0.28,
      'uncertainty_tolerance': 0.88,
      'disclosure_pace': 0.55,
      'boundary_firmness': 0.48,
      'repair_style': 0.58,
      'social_energy': 0.62,
      'structure_preference': 0.32,
      'adaptability': 0.75,
    },
    'kararli': {
      'contact_need': 0.45,
      'closeness_pace': 0.42,
      'initiative': 0.75,
      'autonomy': 0.60,
      'reassurance_need': 0.30,
      'uncertainty_tolerance': 0.35,
      'disclosure_pace': 0.40,
      'boundary_firmness': 0.72,
      'repair_style': 0.50,
      'social_energy': 0.48,
      'structure_preference': 0.80,
      'adaptability': 0.30,
    },
    'vizyoner': {
      'contact_need': 0.48,
      'closeness_pace': 0.48,
      'initiative': 0.68,
      'autonomy': 0.65,
      'reassurance_need': 0.30,
      'uncertainty_tolerance': 0.85,
      'disclosure_pace': 0.50,
      'boundary_firmness': 0.42,
      'repair_style': 0.48,
      'social_energy': 0.52,
      'structure_preference': 0.28,
      'adaptability': 0.82,
    },
    'yaratici': {
      'contact_need': 0.48,
      'closeness_pace': 0.50,
      'initiative': 0.62,
      'autonomy': 0.72,
      'reassurance_need': 0.35,
      'uncertainty_tolerance': 0.78,
      'disclosure_pace': 0.58,
      'boundary_firmness': 0.38,
      'repair_style': 0.50,
      'social_energy': 0.55,
      'structure_preference': 0.22,
      'adaptability': 0.88,
    },
    'iletisimci': {
      'contact_need': 0.75,
      'closeness_pace': 0.70,
      'initiative': 0.65,
      'autonomy': 0.38,
      'reassurance_need': 0.40,
      'uncertainty_tolerance': 0.52,
      'disclosure_pace': 0.88,
      'boundary_firmness': 0.40,
      'repair_style': 0.68,
      'social_energy': 0.82,
      'structure_preference': 0.42,
      'adaptability': 0.58,
    },
    'analist': {
      'contact_need': 0.32,
      'closeness_pace': 0.30,
      'initiative': 0.45,
      'autonomy': 0.70,
      'reassurance_need': 0.28,
      'uncertainty_tolerance': 0.42,
      'disclosure_pace': 0.28,
      'boundary_firmness': 0.65,
      'repair_style': 0.42,
      'social_energy': 0.32,
      'structure_preference': 0.78,
      'adaptability': 0.38,
    },
    'donusturucu': {
      'contact_need': 0.52,
      'closeness_pace': 0.55,
      'initiative': 0.72,
      'autonomy': 0.55,
      'reassurance_need': 0.32,
      'uncertainty_tolerance': 0.80,
      'disclosure_pace': 0.55,
      'boundary_firmness': 0.45,
      'repair_style': 0.62,
      'social_energy': 0.58,
      'structure_preference': 0.30,
      'adaptability': 0.92,
    },
    'bagimsiz': {
      'contact_need': 0.22,
      'closeness_pace': 0.25,
      'initiative': 0.55,
      'autonomy': 0.92,
      'reassurance_need': 0.18,
      'uncertainty_tolerance': 0.62,
      'disclosure_pace': 0.30,
      'boundary_firmness': 0.78,
      'repair_style': 0.38,
      'social_energy': 0.35,
      'structure_preference': 0.48,
      'adaptability': 0.52,
    },
    'sezgisel': {
      'contact_need': 0.55,
      'closeness_pace': 0.58,
      'initiative': 0.40,
      'autonomy': 0.52,
      'reassurance_need': 0.48,
      'uncertainty_tolerance': 0.72,
      'disclosure_pace': 0.52,
      'boundary_firmness': 0.42,
      'repair_style': 0.55,
      'social_energy': 0.45,
      'structure_preference': 0.35,
      'adaptability': 0.68,
    },
    'stratejist': {
      'contact_need': 0.42,
      'closeness_pace': 0.40,
      'initiative': 0.70,
      'autonomy': 0.62,
      'reassurance_need': 0.28,
      'uncertainty_tolerance': 0.65,
      'disclosure_pace': 0.38,
      'boundary_firmness': 0.68,
      'repair_style': 0.48,
      'social_energy': 0.45,
      'structure_preference': 0.75,
      'adaptability': 0.55,
    },
  };

  static Map<String, double> requireUnitTarget(String personaId) {
    final row = unitTargets[personaId];
    if (row == null) {
      throw StateError('Missing Persona V2 Frequency target for $personaId');
    }
    for (final id in PersonaV2Contract.frequencyV2) {
      final v = row[id];
      if (v == null || !v.isFinite || v < 0 || v > 1) {
        throw StateError('Invalid V2 target $personaId.$id');
      }
    }
    return Map<String, double>.unmodifiable(row);
  }
}
