'use strict';

/** Dormant Frequency V2 server contract pins (mirrors Dart FrequencyBehaviorV2Contract). */

const CATALOG_VERSION = 'frequency_behavior_v2_catalog_v1';
const SCHEMA_VERSION = 'frequency_behavior_v2_finalize_session_v1';
const SCORING_POLICY_VERSION = 'frequency_behavior_12d_signed_evidence_v2';
const SELECTION_POLICY_VERSION =
  'frequency_behavior_50_of_426_seeded_quota_v2_draft1';
const SELECTOR_VERSION = 'frequency_behavior_v2_selector_v1';
const SCORER_VERSION = 'frequency_behavior_v2_scorer_v1';
const CONFIDENCE_MODEL_VERSION = 'frequency_behavior_v2_confidence_v1';
const SELECTOR_RNG_ALGORITHM_VERSION = 'xorshift32_fnv1a32_v1';
const SESSION_MANIFEST_SCHEMA_VERSION =
  'qmatch_frequency_behavior_v2_session_manifest_v1';
const SESSION_SCORE_SCHEMA_VERSION =
  'qmatch_frequency_behavior_v2_session_score_v1';
const POOL_VERSION_TR = 'frequency_behavior_pool_tr_v2_draft1';
const POOL_VERSION_EN = 'frequency_behavior_pool_en_v2_draft1';
const LOCALE_TR = 'tr-TR';
const LOCALE_EN = 'en-US';
const TRANSLATION_VERSION_EN = 'frequency_v2_en_semantic_v1';
const ASSESSMENT_TYPE = 'frequency_v2';

const SESSION_BASE_PER_DIMENSION = 4;
const SESSION_FLEX_SLOTS = 2;
const SESSION_ITEM_COUNT = 50;
const MAX_CONSECUTIVE_SAME_PRIMARY = 2;
const SOFT_CLUSTER_LOOKAHEAD = 2;
const POOL_ITEM_COUNT = 426;
const POOL_OPTION_COUNT = 1704;
const SELECTABLE_ITEM_COUNT = 405;
const DROP_ITEM_COUNT = 21;
const DIMENSION_COUNT = 12;

const CONFIDENCE_EVIDENCE_WEIGHT = 0.5;
const CONFIDENCE_OBSERVABILITY_WEIGHT = 0.3;
const CONFIDENCE_CONTEXT_WEIGHT = 0.2;
const PRESENTATION_PRESSURE_MAX_DISCOUNT = 0.2;
const FLAG_LOW_EVIDENCE_QUALITY_MAX = 0.5;
const FLAG_HIGH_PRESENTATION_PRESSURE_MIN = 0.75;
const FLAG_LOW_PRIMARY_OBSERVABILITY_MAX = 0.5;
const FLAG_LIMITED_CROSS_CONTEXT_COVERAGE_MAX = 0.5;
const FLAG_CONTEXT_SENSITIVE_CONSISTENCY_MAX = 0.5;
const FLAG_CONTEXT_SENSITIVE_COVERAGE_MIN = 0.5;

const FLAG_LOW_EVIDENCE_QUALITY = 'LOW_EVIDENCE_QUALITY';
const FLAG_HIGH_PRESENTATION_PRESSURE = 'HIGH_PRESENTATION_PRESSURE';
const FLAG_LOW_PRIMARY_OBSERVABILITY = 'LOW_PRIMARY_OBSERVABILITY';
const FLAG_LIMITED_CROSS_CONTEXT = 'LIMITED_CROSS_CONTEXT';
const FLAG_CONTEXT_SENSITIVE = 'CONTEXT_SENSITIVE';

const CANONICAL_DIMENSIONS = Object.freeze([
  'contact_need',
  'closeness_pace',
  'initiative',
  'autonomy',
  'reassurance_need',
  'uncertainty_tolerance',
  'disclosure_pace',
  'boundary_firmness',
  'repair_style',
  'social_energy',
  'structure_preference',
  'adaptability',
]);

const CANONICAL_DIMENSION_SET = new Set(CANONICAL_DIMENSIONS);

const PAIR_FIT_VERSION = 'frequency_behavior_v2_pair_fit_v1';
const PAIR_FIT_POLICY_VERSION = 'frequency_pair_fit_policy_v1';
const PAIR_RELATION_VERSION = 'frequency_behavior_v2_pair_relation_v1';
const PAIR_FIT_POLICY_SIMILARITY_LINEAR = 'SIMILARITY_LINEAR';
const PAIR_FIT_POLICY_SIMILARITY_TOLERANT = 'SIMILARITY_TOLERANT';
const PAIR_FIT_LINEAR_POLICY_DIMENSIONS = Object.freeze([
  'contact_need',
  'closeness_pace',
  'autonomy',
  'reassurance_need',
  'uncertainty_tolerance',
  'disclosure_pace',
  'boundary_firmness',
  'repair_style',
]);
const PAIR_FIT_TOLERANT_POLICY_DIMENSIONS = Object.freeze([
  'initiative',
  'social_energy',
  'structure_preference',
  'adaptability',
]);
const PAIR_FIT_LINEAR_POLICY_DIMENSION_SET = new Set(
  PAIR_FIT_LINEAR_POLICY_DIMENSIONS,
);
const PAIR_FIT_TOLERANT_POLICY_DIMENSION_SET = new Set(
  PAIR_FIT_TOLERANT_POLICY_DIMENSIONS,
);

const RESULT_SCHEMA_VERSION = 'qmatch_frequency_behavior_v2_result_v1';
const RESULT_SOURCE = 'admin_finalize_frequency_v2_v1';
const RESULT_STATUS = 'completed';
const RESULT_DOC_ID = 'frequency_v2';

function isCanonicalDimension(id) {
  return CANONICAL_DIMENSION_SET.has(id);
}

module.exports = {
  CATALOG_VERSION,
  SCHEMA_VERSION,
  SCORING_POLICY_VERSION,
  SELECTION_POLICY_VERSION,
  SELECTOR_VERSION,
  SCORER_VERSION,
  CONFIDENCE_MODEL_VERSION,
  SELECTOR_RNG_ALGORITHM_VERSION,
  SESSION_MANIFEST_SCHEMA_VERSION,
  SESSION_SCORE_SCHEMA_VERSION,
  POOL_VERSION_TR,
  POOL_VERSION_EN,
  LOCALE_TR,
  LOCALE_EN,
  TRANSLATION_VERSION_EN,
  ASSESSMENT_TYPE,
  SESSION_BASE_PER_DIMENSION,
  SESSION_FLEX_SLOTS,
  SESSION_ITEM_COUNT,
  MAX_CONSECUTIVE_SAME_PRIMARY,
  SOFT_CLUSTER_LOOKAHEAD,
  POOL_ITEM_COUNT,
  POOL_OPTION_COUNT,
  SELECTABLE_ITEM_COUNT,
  DROP_ITEM_COUNT,
  DIMENSION_COUNT,
  CONFIDENCE_EVIDENCE_WEIGHT,
  CONFIDENCE_OBSERVABILITY_WEIGHT,
  CONFIDENCE_CONTEXT_WEIGHT,
  PRESENTATION_PRESSURE_MAX_DISCOUNT,
  FLAG_LOW_EVIDENCE_QUALITY_MAX,
  FLAG_HIGH_PRESENTATION_PRESSURE_MIN,
  FLAG_LOW_PRIMARY_OBSERVABILITY_MAX,
  FLAG_LIMITED_CROSS_CONTEXT_COVERAGE_MAX,
  FLAG_CONTEXT_SENSITIVE_CONSISTENCY_MAX,
  FLAG_CONTEXT_SENSITIVE_COVERAGE_MIN,
  FLAG_LOW_EVIDENCE_QUALITY,
  FLAG_HIGH_PRESENTATION_PRESSURE,
  FLAG_LOW_PRIMARY_OBSERVABILITY,
  FLAG_LIMITED_CROSS_CONTEXT,
  FLAG_CONTEXT_SENSITIVE,
  CANONICAL_DIMENSIONS,
  CANONICAL_DIMENSION_SET,
  PAIR_FIT_VERSION,
  PAIR_FIT_POLICY_VERSION,
  PAIR_RELATION_VERSION,
  PAIR_FIT_POLICY_SIMILARITY_LINEAR,
  PAIR_FIT_POLICY_SIMILARITY_TOLERANT,
  PAIR_FIT_LINEAR_POLICY_DIMENSIONS,
  PAIR_FIT_TOLERANT_POLICY_DIMENSIONS,
  PAIR_FIT_LINEAR_POLICY_DIMENSION_SET,
  PAIR_FIT_TOLERANT_POLICY_DIMENSION_SET,
  RESULT_SCHEMA_VERSION,
  RESULT_SOURCE,
  RESULT_STATUS,
  RESULT_DOC_ID,
  isCanonicalDimension,
};
